// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20210122190745_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Name");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = "2 years old",
                            Breed = "Russian Blue",
                            Name = "Charlie"
                        },
                        new
                        {
                            CatId = 2,
                            Age = "10 years old",
                            Breed = "Tabby",
                            Name = "Max"
                        },
                        new
                        {
                            CatId = 3,
                            Age = "6 months old",
                            Breed = "Siamese",
                            Name = "Barry"
                        });
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Name");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = "12 years old",
                            Breed = "German Shepard",
                            Name = "Kika"
                        },
                        new
                        {
                            DogId = 2,
                            Age = "6 years old",
                            Breed = "Pitbull Mix",
                            Name = "Daisy"
                        },
                        new
                        {
                            DogId = 3,
                            Age = "3 months old",
                            Breed = "Siberian Husky",
                            Name = "Maya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
